### PR TITLE
Do not remove the IPC files when logging out

### PR DESCRIPTION
**Pull request by juagargi**
# Needs testing
I didn't know if we have a mechanism to test this against e.g. a VM, but for sure it has to be tested before merging.
Also, close https://github.com/netsec-ethz/scion-web/issues/137 when merged (scion-web).

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-deploy/47)

### CODE REVIEW

**Comment by mkowalski** [comment]
I would avoid using directly `echo >>` as it's not checking anything regarding whether this option already exists. How about something as below? It will check whether this option is already set, regardless of its value, and set to the one you want.
```
- lineinfile:
    path: /etc/systemd/logind.conf
    regexp: '^RemoveIPC'
    line: 'RemoveIPC=no'
  become: true
```

Also `become_user: root` is not necessary, `become: true` by default chooses root.

**Comment by matzf** [comment]
Just to mention it; this RemoveIPC dance can be avoided if we'd create our user as "system user" (`useradd -r` or in ansible `ansible/roles/basic/tasks/basic.yml`, `user: system: yes`).

**Comment by mkowalski** [comment]
This is true, however for systems where the user has already been created, the process of making "normal" user a "system" one would be too painful to recommend it as a way to go.

For any new deployments though, this is true, the deployment manifest should create the user as "system" and logind should not be reconfigured.

**Comment by juagargi** [comment]
@mkowalski could you prepare or review our deployment process to create a system user? The playbook could remove the user if existing, etc. We are in a position where we can make changes to the nodes we need, in order for us to re-deploy cleanly :)

**Comment by mkowalski** [comment]
`ansible/roles/basic/tasks/basic.yml` should be changed as @matzf mentioned already, but this is only for the new deployments - I guess this playbook is not meant to be run against machines which are already up and running, isn't it?

There should be a separate, one shot, playbook to apply the change we want to perform, i.e. change UID, change GID, change permissions across the whole filesystem.

One more thing we need to remember is to ensure the system user we create does not get `nologin` as its shell.

I will prepare what's needed here and create a new MR with everything packed.

**Comment by mkowalski** [comment]
@juagargi, how widely spread is this issue and who in reality is affected? As discussed some time ago with @matzf, none of those solutions is elegant. We should follow the pattern any other service does and aim for having a separate user only for running scion (it should not be used for interactive sessions).

**Comment by matzf** [comment]
Repository archived, closed.

**Pull request closed without merging**
