### PR TITLE
Enable key-less SCION deployment.

### PR DESCRIPTION
**Pull request by ercanucan**
- This PR enables key-less installation of SCION in the simple configuration mode
where all ASes run on a single machine.

Invoking deploy.yml as below will install SCION on the local machine without any keys required:
ansible-playbook deploy.yml -i <host_file> --connection=local --extra-vars='simple_conf=True' --ask-become-pass

- Includes simple refactoring of the existing roles (scion_node and basic) in order
to implement the feature.
- Removes the default zoo.cfg file as this is generated by scion-web.

Can be used once the following PRs are merged:
- https://github.com/netsec-ethz/scion-web/pull/74
- https://github.com/netsec-ethz/scion-web/pull/75

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-deploy/38)

### CODE REVIEW

**Comment by ercanucan** [comment]
@klausman or @kormat

**Comment by ercanucan** [comment]
Review status: 10 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[ansible/roles/scion_node/tasks/scion_node.yml, line 7 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KidTD8Uy_rL4V-QtBKq:-Kj3UuCQ1dpZ20bWwKXO:bpq1pqd) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/69108356d01257758a801ba12b3acdf2f98db4e0/ansible/roles/scion_node/tasks/scion_node.yml#L7)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

I'm not sure we want to always install this key. Could it be moved to a different playbook that also installs the VPN-GW sources?
</blockquote></details>

Makes sense. Removed it from the playbook as SIG will take its place anyway.

---

*[ansible/roles/scion_node/tasks/scion_node.yml, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KidTY4oP6FsYm6UIpGP:-Kj3V57Aim78M9cDqr-C:b-r85w47) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/69108356d01257758a801ba12b3acdf2f98db4e0/ansible/roles/scion_node/tasks/scion_node.yml#L25)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Since the main repo is public, this could be `https://`, I think. That would also obviate the need for the deployment key.

@kormat Agreed?
</blockquote></details>

Agree. Done. Switched to the `https://` deployment. After addressing your feedback, there's no need to have a separate file for simple config with the `scion_node` role (for `basic` role it's still necessary). Adapted accordingly.

---

*[ansible/roles/scion_node/tasks/scion_node.yml, line 31 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KidTgzuUHlv6-B6jieR:-Kj3VVUP0jj6DfZC8qSQ:b-i490ef) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/69108356d01257758a801ba12b3acdf2f98db4e0/ansible/roles/scion_node/tasks/scion_node.yml#L31)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Again, this can likely moved to a VPN-GW specific playbook.
</blockquote></details>

Agree, removed this as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38)*

**Comment by ercanucan** [comment]
@klausman ping

**Comment by klausman** [comment]
:lgtm: from me, unsure about @kormat  

---

Reviewed 4 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-:-KjIsrc2jxrKjUxQcguo:bellwjk)*

**Comment by ercanucan** [comment]
@kormat ping

**Comment by kormat** [comment]
Reviewed 10 of 15 files at r1, 4 of 5 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[ansible/deploy.yml, line 84 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjN9d6DTYiuDt4HHneO:-KjN9d6DTYiuDt4HHneP:bow1qam) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/deploy.yml#L84)):*
> ```YAML
>   remote_user: scion
>   become: true
>   become_user: scion
> ```

This looks.. odd. Does this mean that in the normal setup, ansible will ssh as scion, then sudo to scion?

Would something like this work?  `become: simple_conf|default(false)|bool == true`

---

*[ansible/roles/basic/tasks/simple_conf_basic.yml, line 27 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNCDaEjs97X3R1KDPo:-KjNCDaEjs97X3R1KDPp:bxkn1ry) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/basic/tasks/simple_conf_basic.yml#L27)):*
> ```YAML
>   - name: Install setfacl Support
>     apt: pkg=acl
>   become: true
> ```

Move this to the top of the `block` so that it's more obvious. Same applies for other block-level settings.

---

*[ansible/roles/scion_node/tasks/main.yml, line 5 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNDO4NlZyG4EjVR9iP:-KjNDO4NlZyG4EjVR9iQ:b-xsrv3v) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/scion_node/tasks/main.yml#L5)):*
> ```YAML
>   - name: Install pre-deps
>     apt: name=git
>   - name: Configure Git to use HTTPS Protocol
> ```

This only works if we're no longer going to deploy any private code anywhere...

---

*[ansible/roles/scion_node/tasks/main.yml, line 20 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNDXAoMwbJOx8YdvQ7:-KjNDXAoMwbJOx8YdvQ8:biocmuo) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/scion_node/tasks/main.yml#L20)):*
> ```YAML
>     file: path={{repo_loc}} state=directory
>   - name: Checkout SCION codebase
>     git: repo=https://github.com/netsec-ethz/scion.git
> ```

This change is made unnecessary by the `insteadOf` above.

---

*[ansible/roles/scion_node/tasks/main.yml, line 26 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNE1suS8zNgXoRdnXK:-KjNE1suS8zNgXoRdnXL:bvp701e) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/scion_node/tasks/main.yml#L26)):*
> ```YAML
>          accept_hostkey=yes
>   - name: Install all dependencies
>     # TODO(ercanucan): Will be changed to ./env/deps for versions newer than9c8a577b3a712a6280a250e4d505a54a9ecb9be8
> ```

Space missing after "than".

---

*[ansible/roles/scion_node/tasks/main.yml, line 33 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNE8V01GQIGOG-AmCR:-KjNE8V01GQIGOG-AmCS:b-dfaaa3) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/scion_node/tasks/main.yml#L33)):*
> ```YAML
>     copy: src={{local_gen}}/ISD{{isd}}/AS{{as}}/endhost  dest={{repo_loc}}/gens/{{ts}}/ISD{{isd}}/AS{{as}}/
>   become: true
>   become_user: scion
> ```

In the normal setup, this means ssh'ing in as root, and then sudo'ing to scion, which isn't great.

---

*[ansible/roles/zk/handlers/main.yml, line 4 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNEUlLdB9IlYSRkWQC:-KjNEUlLdB9IlYSRkWQD:b-qqd2io) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/zk/handlers/main.yml#L4)):*
> ```YAML
> - name: restart zookeeper
>   service: name=zookeeper state=restarted
>   become: true
> ```

For the normal deployment, this will ssh in as root and then.. sudo to root.

---

*[ansible/roles/scion_node/tasks/scion_node.yml, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KidTY4oP6FsYm6UIpGP:-KjNEmsxa6BlQk4ujknb:bg2e5it) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/69108356d01257758a801ba12b3acdf2f98db4e0/ansible/roles/scion_node/tasks/scion_node.yml#L25)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Agree. Done. Switched to the `https://` deployment. After addressing your feedback, there's no need to have a separate file for simple config with the `scion_node` role (for `basic` role it's still necessary). Adapted accordingly.
</blockquote></details>

@klausman - i'm not convinced. In the near-to-mid term, i would expect us to have private repos for some stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38)*

**Comment by ercanucan** [comment]
Review status: 3 of 15 files reviewed at latest revision, 8 unresolved discussions.

---

*[ansible/deploy.yml, line 84 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjN9d6DTYiuDt4HHneO:-Kjx-muo9GK88jC-IIlO:bjy2afv) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/deploy.yml#L84)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This looks.. odd. Does this mean that in the normal setup, ansible will ssh as scion, then sudo to scion?

Would something like this work?  `become: simple_conf|default(false)|bool == true`
</blockquote></details>

No, that doesn't work. But this does: `become: "{{simple_conf|default(false)}}"`. Adapted the other `become` statements as necessary.

---

*[ansible/roles/basic/tasks/simple_conf_basic.yml, line 27 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNCDaEjs97X3R1KDPo:-Kjx-xpMnHo8TaxZ3veB:b-k9g0jz) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/basic/tasks/simple_conf_basic.yml#L27)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Move this to the top of the `block` so that it's more obvious. Same applies for other block-level settings.
</blockquote></details>

That's not a valid syntax. `block` expects the `become` statement at the end of the task list. Instead, I added a new-line to make it a little more obvious.

---

*[ansible/roles/scion_node/tasks/main.yml, line 5 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNDO4NlZyG4EjVR9iP:-KjxNP8Iy5djU-2C_tyP:b-tbab0a) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/scion_node/tasks/main.yml#L5)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This only works if we're no longer going to deploy any private code anywhere...
</blockquote></details>

Okay. So I changed back the `scion_node`to be key-based for the normal deployment case. Adapted the role accordingly. Now its layout looks similar to the `basic` role.

---

*[ansible/roles/scion_node/tasks/main.yml, line 20 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNDXAoMwbJOx8YdvQ7:-KjxN_9534CapfrfdixG:bvosij9) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/scion_node/tasks/main.yml#L20)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This change is made unnecessary by the `insteadOf` above.
</blockquote></details>

This is only in the `simple_conf_scion_node.yml` now. (I agree that it does not matter whether this is `git@github.com` or `https://github.com`as we have the `insteadOf` above). We do need the `insteadOf` though, otherwise the submodules could not be checked out in a key-less manner.

---

*[ansible/roles/scion_node/tasks/main.yml, line 26 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNE1suS8zNgXoRdnXK:-KjxFcLxCaP0IiAvPbBo:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/scion_node/tasks/main.yml#L26)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Space missing after "than".
</blockquote></details>

Done.

---

*[ansible/roles/scion_node/tasks/main.yml, line 33 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNE8V01GQIGOG-AmCR:-KjxKW2j9p8Jcw7mz_PX:bbn1rpo) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/scion_node/tasks/main.yml#L33)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

In the normal setup, this means ssh'ing in as root, and then sudo'ing to scion, which isn't great.
</blockquote></details>

Addressed. The normal setup does not have this anymore. Now we have two separate task lists for normal deployment and simple deployment.

---

*[ansible/roles/scion_node/tasks/scion_node.yml, line 25 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KidTY4oP6FsYm6UIpGP:-KjxFvt95ye2qGgwfwUJ:b-bang1d) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/69108356d01257758a801ba12b3acdf2f98db4e0/ansible/roles/scion_node/tasks/scion_node.yml#L25)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

@klausman - i'm not convinced. In the near-to-mid term, i would expect us to have private repos for some stuff.
</blockquote></details>

Answered above.

---

*[ansible/roles/zk/handlers/main.yml, line 4 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-KjNEUlLdB9IlYSRkWQC:-KjxG_7jtLec_X1EY9Eb:b-9s26v5) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/8484788bec48189de18edee79fc1c0e27a77248a/ansible/roles/zk/handlers/main.yml#L4)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

For the normal deployment, this will ssh in as root and then.. sudo to root.
</blockquote></details>

Changed to `become: "{{simple_conf|default(false)}}"` throughout the PR according to your suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38)*

**Comment by ercanucan** [comment]
@kormat addressed your comments. ready for another review

---

Review status: 3 of 15 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-:-KjyA8nYUIF4EaBB4obj:b-sk7gys)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-:-KkBITheLFZEq86fTeRi:bnfp4nl)*

**Comment by klausman** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/38#-:-KkBONfnS4vNgG1OQDxg:bnfp4nl)*

**Comment by ercanucan** [comment]
thanks!

**Pull request merged**
