### PR TITLE
Add a Netfilter rule generator

### PR DESCRIPTION
**Pull request by klausman**
@kormat

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-deploy/33)

### CODE REVIEW

**Comment by kormat** [comment]
Holding off on reviewing this until it's switched to use the new yaml input format.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/netfilter/.gitignore, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kcci3pxepKbCvcdE_Zd:-Kcci3pxepKbCvcdE_Ze:baivgmo) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/70da150701670acf1d0cc920f801250c2a98ad30/ansible/netfilter/.gitignore#L1)):*
> ```
> gen/*.scionproto.net
> ```

What files are likely to be in `gen/` that don't match that pattern?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-:-KcciBes8KIS093g5Edj:b-mvlu5r)*

**Comment by klausman** [comment]
Completely new version using the INI inventory.

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/netfilter/.gitignore, line 1 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kcci3pxepKbCvcdE_Zd:-Kdf64nCMttKodL21cuN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/70da150701670acf1d0cc920f801250c2a98ad30/ansible/netfilter/.gitignore#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

What files are likely to be in `gen/` that don't match that pattern?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-:-Kdf67rRy1rAiofRaGzI:b-97tsy2)*

**Comment by kormat** [comment]
Reviewed 1 of 6 files at r1, 4 of 6 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[ansible/netfilter/mkrules.py, line 11 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdfbdBgWDfYCvSHnwAO:-KdfbdBgWDfYCvSHnwAP:bl0vjn4) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L11)):*
> ```Python
> def mkisdasranges(filename):
>     """
>     Read inventory INI file and create mappins between ISDs and IP ranges
> ```

"mappins" -> "mappings"
"ISDs" -> "SCION ASes" (or "ISD-ASes")

---

*[ansible/netfilter/mkrules.py, line 14 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kdfbq1KF0P5_OPWnzAX:-Kdfbq1KF0P5_OPWnzAY:b-hf340m) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L14)):*
> ```Python
> 
>     Returns four dictionaries: IP address to ISD-AS, ISD-AS to set of IP
>     ranges, IP address to owner and IP address to FQDN.
> ```

Oxford comma missing.

---

*[ansible/netfilter/mkrules.py, line 32 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdfcXUj7FEsGE5FxbGZ:-KdfcXUkrT3ffyXZjrUh:b7btzyo) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L32)):*
> ```Python
>             ip2fqdn[ipaddr] = fqdn
>         else:
>             if "isd_as" in parser[section]:
> ```

Merge into `elif`?

---

*[ansible/netfilter/mkrules.py, line 36 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kdfc8l6M7d5yh-3NQbQ:-Kdfc8l6M7d5yh-3NQbR:b-49grml) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L36)):*
> ```Python
> 
>     for ipaddr, fqdn in ip2fqdn.items():
>         owner = fqdn.split(".")[2]
> ```

It's worth mentioning the owner in the ini format description.

---

*[ansible/netfilter/mkrules.py, line 38 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdflZHv7Lybp6ZIZYph:-KdflZHv7Lybp6ZIZYpi:b2nhpzb) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L38)):*
> ```Python
>         owner = fqdn.split(".")[2]
>         ip2owner[ipaddr] = owner
>         ip2fqdn[ipaddr] = fqdn
> ```

Uh?

---

*[ansible/netfilter/mkrules.py, line 59 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kdfmd1kNUZw-9DcKZKe:-Kdfmd1kNUZw-9DcKZKf:b-vvh95a) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L59)):*
> ```Python
>     """Main program"""
>     ip2isdas, isdas2ranges, ip2owner, ip2fqdn = mkisdasranges(sys.argv[1])
>     with open("rulesets/minimal") as fd:
> ```

Quibble `fd` isn't a file descriptor. `f` would be slightly better (and more idiomatic). Same for `outfd` below.

---

*[ansible/netfilter/README.md, line 14 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kdfax4w94NVA5AHDQgh:-Kdfax4xYf-2-fNYDVi_:bgtg8eb) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/README.md#L14)):*
> ```Markdown
> - `gen/` is a subdirectory that will hold the generated files.
> 
> ## Inventory file format
> ```

We might need to move this somewhere else if we add more tooling based on the format elsewhere in the repo, but for now i think it's ok where it is.

---

*[ansible/netfilter/README.md, line 26 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdfbDHon2psAjUibnHe:-KdfbDHpoa8OgtDS82kR:b-hqe7vh) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/README.md#L26)):*
> a positive integer.
a non-negative integer.

---

*[ansible/netfilter/README.md, line 54 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdfbRtat_4wLIPpG0tw:-KdfbRtat_4wLIPpG0tx:bx8mf1a) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/README.md#L54)):*
> ```Markdown
> 
> The interface section associates network configuration information with the
> FQDN. It us named `<fqdn>:iface:<#>`, where # is an integer number that has not
> ```

"has no"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33)*

**Comment by klausman** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[ansible/netfilter/mkrules.py, line 11 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdfbdBgWDfYCvSHnwAO:-KdjEYP05ZFQ9gxU8LID:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L11)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"mappins" -> "mappings"
"ISDs" -> "SCION ASes" (or "ISD-ASes")
</blockquote></details>

Done.

---

*[ansible/netfilter/mkrules.py, line 14 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kdfbq1KF0P5_OPWnzAX:-KdjEaoxFBynuA5OE-W3:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L14)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Oxford comma missing.
</blockquote></details>

Done.

---

*[ansible/netfilter/mkrules.py, line 32 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdfcXUj7FEsGE5FxbGZ:-KdjEf8wPGliDUg6PMkH:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L32)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Merge into `elif`?
</blockquote></details>

Done.

---

*[ansible/netfilter/mkrules.py, line 36 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kdfc8l6M7d5yh-3NQbQ:-KdjF34QdNkplMvvFZff:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L36)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It's worth mentioning the owner in the ini format description.
</blockquote></details>

Done.

---

*[ansible/netfilter/mkrules.py, line 38 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdflZHv7Lybp6ZIZYph:-KdjF9oPTZLt-YnmWCnf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L38)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Uh?
</blockquote></details>

Done.

---

*[ansible/netfilter/mkrules.py, line 59 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-Kdfmd1kNUZw-9DcKZKe:-KdjFKZHsZeMTemKf_nB:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/mkrules.py#L59)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Quibble `fd` isn't a file descriptor. `f` would be slightly better (and more idiomatic). Same for `outfd` below.
</blockquote></details>

Done.

---

*[ansible/netfilter/README.md, line 26 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdfbDHon2psAjUibnHe:-KdjFnw862-FcfNXmcuV:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/README.md#L26)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

> a positive integer.
a non-negative integer.
</blockquote></details>

Done.

---

*[ansible/netfilter/README.md, line 54 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-KdfbRtat_4wLIPpG0tw:-KdjFoKqsq3pWQ5w2BHw:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/91f71b92fd08cfb7bd685ca72f57714b6c7d2bf0/ansible/netfilter/README.md#L54)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"has no"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/33#-:-Kdz8Eg8fUr1hZu_kRZV:bnfp4nl)*

**Pull request merged**
