### PR TITLE
Add finalize.sh to clean up packages post-install

### PR DESCRIPTION
**Pull request by klausman**
@kormat

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-deploy/31)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[preseed/finalize.sh, line 12 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31#-KbULAlynU40US0An4GU:-KbULAlz6_sKoKgULjJl:b-g5rkbu) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/f2e800ccf48095c4ed14c34993f2a203f6c16648/preseed/finalize.sh#L12)):*
> ```Shell
> 
> log "Pruning packages"
> 	apt purge --no-install-recommends -u $REMOVE
> ```

Leading tab? Also no need to specify the `--no-install-recommends` flag here.
`-u` also only applies to upgrades, and is also the default (since 2003 according to https://lists.debian.org/deity/2016/05/msg00072.html).

---

*[preseed/finalize.sh, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31#-KbULTk060hcrjeYdzux:-KbULTk060hcrjeYdzuy:bhqvztp) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/f2e800ccf48095c4ed14c34993f2a203f6c16648/preseed/finalize.sh#L15)):*
> ```Shell
> log "Done pruning packages"
> 
> # We likely removed resolvconf, so we have to fix the DNS config before
> ```

What about making a copy of `resolv.conf` before removing `resolvconf`, and restoring the copy? The benefit of your approach is that it _should_ work for any env. The downside is that things like split-horizon DNS won't work, which may cause confusion in some environments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31)*

**Comment by klausman** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[preseed/finalize.sh, line 12 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31#-KbULAlynU40US0An4GU:-KbUjXNvQ5UQ2uPd4G3J:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/f2e800ccf48095c4ed14c34993f2a203f6c16648/preseed/finalize.sh#L12)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Leading tab? Also no need to specify the `--no-install-recommends` flag here.
`-u` also only applies to upgrades, and is also the default (since 2003 according to https://lists.debian.org/deity/2016/05/msg00072.html).
</blockquote></details>

Done.

---

*[preseed/finalize.sh, line 15 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31#-KbULTk060hcrjeYdzux:-KbUkAmLenTFiSPf89_i:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/f2e800ccf48095c4ed14c34993f2a203f6c16648/preseed/finalize.sh#L15)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

What about making a copy of `resolv.conf` before removing `resolvconf`, and restoring the copy? The benefit of your approach is that it _should_ work for any env. The downside is that things like split-horizon DNS won't work, which may cause confusion in some environments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31)*

**Comment by kormat** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[preseed/finalize.sh, line 30 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31#-KbUm5xoTnV6YbRHS-XV:-KbUm5xp0Br1SMc2t2AZ:bbu1tlm) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/e47ef3a273a76f75c94198113adbec4cf13d0155/preseed/finalize.sh#L30)):*
> ```Shell
> 
> log "Cleaning up unneeded packages"
> apt -u --purge autoremove
> ```

`-u` is still in these last two apt commands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31)*

**Comment by klausman** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[preseed/finalize.sh, line 30 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31#-KbUm5xoTnV6YbRHS-XV:-KbUn_6-lMxridFWBRZo:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/e47ef3a273a76f75c94198113adbec4cf13d0155/preseed/finalize.sh#L30)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`-u` is still in these last two apt commands.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31)*

**Comment by kormat** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/31#-:-KbUpYodHGa0wOjQztZZ:bnfp4nl)*

**Pull request merged**
