### PR TITLE
Clear gen-cache before starting the infrastructure

### PR DESCRIPTION
**Pull request by ercanucan**
This PR clears the gen-cache so that stale certificates (if any) will be removed from the cache.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-deploy/42)

### CODE REVIEW

**Comment by kormat** [comment]
This defeats the purpose of the `gen-cache` folder. In the longer term, we would have cert renewal, which would remove this issue. In the meantime, this should only be done if certs have been re-made. How often does that occur?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/42#-:-KvWC02CxWM44uZW_COt:b-abp0hi)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/42)*

**Comment by ercanucan** [comment]
It's difficult to give an exact number as it depends on the changes coming into the Certificate related code in the main code-base, but at our current rate a couple to a few times a year. 
I made this an option now to the `deploy.yml` playbook, defaulting to false.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/42#-:-KvbtLYRXvDiI3fk6f2Y:bteve4y)*

**Comment by kormat** [comment]
:lgtm:

Bear in mind that any time this is used, you'll also need to clear all ZK caches.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/42#-:-KvbzVEpL5e1hUioWjNW:bbniled)*

**Comment by ercanucan** [comment]
Yes, thanks!

**Pull request merged**
