### PR TITLE
Make sure /boot is not too small

### PR DESCRIPTION
**Pull request by klausman**
With the default of <200M, having 4-5 kernels and attendant initramfs's
can easily fill up /boot, requiring manual intervention before any
updates will work.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-deploy/35)

### CODE REVIEW

**Comment by klausman** [comment]
@kormat

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[preseed/xenial.cfg, line 44 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/35#-KdelRF9_qAv71zQ8tel:-KdelRF9_qAv71zQ8tem:bb7fwdy) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/e06ef4c2737886cf049ace669f22ced00c464e86/preseed/xenial.cfg#L44)):*
> ```INI
>                       $primary{ } $bootable{ }                \
>                       method{ format } format{ }              \
>                       use_filesystem{ } filesystem{ ext4 }    \
> ```

ext2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/35)*

**Comment by klausman** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[preseed/xenial.cfg, line 44 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/35#-KdelRF9_qAv71zQ8tel:-KdemucNNUF-tXqAh8Ox:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/e06ef4c2737886cf049ace669f22ced00c464e86/preseed/xenial.cfg#L44)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

ext2
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/35)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/35#-:-Kden0DvL_phxu7TBOSC:bnfp4nl)*

**Pull request merged**
