### PR TITLE
Make user and key setup more strict

### PR DESCRIPTION
**Pull request by klausman**
This ensures that we have *exactly* the keys for root and scion that we
want, instead of the target machine having a non-strict superset of
them.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-deploy/30)

### CODE REVIEW

**Comment by klausman** [comment]
@kormat

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ansible/roles/basic/tasks/main.yml, line 7 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/30#-KaISdv58pThLnQSIJjo:-KaISdv58pThLnQSIJjp:bf042jr) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/e052aac02d89edd884aa8ba297ff8e7ae21fcd9e/ansible/roles/basic/tasks/main.yml#L7)):*
> ```YAML
>     owner: root
>     group: root
>     mode: "u=rwx,g-rwx,o-rwx"
> ```

I think octal permissions are easier to read/verify.

---

*[ansible/roles/basic/tasks/main.yml, line 11 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/30#-KaISvkK-0M8QMSNqMFK:-KaISvkLP5jAdpxciOIL:b-820k88) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/e052aac02d89edd884aa8ba297ff8e7ae21fcd9e/ansible/roles/basic/tasks/main.yml#L11)):*
> ```YAML
> - name: Setup ~root/.ssh/authorized_keys and ensure permissions=0600
>   copy:
>     src: files/ansible.rsa.pub
> ```

Question - what will ansible do if this file doesn't exist?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/30)*

**Comment by klausman** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ansible/roles/basic/tasks/main.yml, line 7 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/30#-KaISdv58pThLnQSIJjo:-KaIU3TnVTvdQ1IFSFE_:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/e052aac02d89edd884aa8ba297ff8e7ae21fcd9e/ansible/roles/basic/tasks/main.yml#L7)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I think octal permissions are easier to read/verify.
</blockquote></details>

Done.

---

*[ansible/roles/basic/tasks/main.yml, line 11 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/30#-KaISvkK-0M8QMSNqMFK:-KaITwp90F9SOfjXFG72:b-gw4mr0) ([raw file](https://github.com/netsec-ethz/scion-deploy/blob/e052aac02d89edd884aa8ba297ff8e7ae21fcd9e/ansible/roles/basic/tasks/main.yml#L11)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Question - what will ansible do if this file doesn't exist?
</blockquote></details>

```
TASK [basic : Setup ~root/.ssh/authorized_keys and ensure permissions=0600] ****
fatal: [scn01.ircl1.uniz.scionproto.net]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'files/ansible.rsa.pubaaaa' in expected paths."}
	to retry, use: --limit @/home/klausman/scion/scion-deploy/ansible/k.retry

PLAY RECAP *********************************************************************
scn01.ircl1.uniz.scionproto.net : ok=2    changed=0    unreachable=0    failed=1 
```

The file on the target machine remains untouched.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/30)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-deploy/30#-:-KaM-QaprFK-nmgv86g3:bnfp4nl)*

**Pull request merged**
